### ISSUE TITLE
Add additional package metadata

### ISSUE THREAD

**Issue by jbw976** [crossplane-contrib/function-kcl#35]
### What happened?

Now that this function-kcl has been published to the marketplace at https://marketplace.upbound.io/functions/crossplane-contrib/function-kcl, we should improve the metadata of this package to provide a more rich experience with more details.

### How can we reproduce it?

Navigate to https://marketplace.upbound.io/functions/crossplane-contrib/function-kcl, and see:

* Overview says "No overview provided."
* Name is `kcl-function`, even though the repo is `function-kcl`.
* Source code field is missing
* maybe others too?
* note that an icon is missing, but the marketplace will be adding that on the backend, so don't worry about that

We can compare this to another function like https://marketplace.upbound.io/functions/crossplane-contrib/function-auto-ready, which has more of these details defined. As an example, the source of its metadata can be found in https://github.com/crossplane-contrib/function-auto-ready/blob/main/package/crossplane.yaml.

### What environment did it happen in?
Function version: v0.2.0

**Comment by Peefy** [comment]
Thank you! I have successfully implemented automatic updates of information and released a new version of crossplane function kcl
![image](https://github.com/crossplane-contrib/function-kcl/assets/22744597/7243d4f0-c8e5-4cd8-9559-8d907a145774)
