### ISSUE TITLE
How do you patch the XR status?

### ISSUE THREAD

**Issue by empath-nirvana** [crossplane-contrib/function-kcl#49]
I've got a pipeline that creates resources, but I need to bubble status back up to the XR. 

Is there an example of how to accomplish basically an ToCompositeFieldPath patch back to the XR using this function or with some other function?

The patch and transform function needs to know the name of the resource and that's not really deterministic.

**Comment by Peefy** [comment]
The XR patching example is here: https://github.com/crossplane-contrib/function-kcl/tree/main/examples/xr/patching. You can path the status field like this PR: https://github.com/crossplane-contrib/function-kcl/pull/50

**Comment by empath-nirvana** [comment]
Thanks, that worked!  Now my problem is that "ocds" doesn't have the status of existing objects and nothing in parameters does.  Is there a way to get access to the status of an existing object?

**Comment by empath-nirvana** [comment]
actually there's a bug, let me open a pr

**Comment by Peefy** [comment]
Thank you! @empath-nirvana PRs welcome!
