### ISSUE TITLE
Support 'Function pipeline context'

### ISSUE THREAD

**Issue by aleeriz** [crossplane-contrib/function-kcl#64]
### What problem are you facing?
It would be really helpful if the function supported [function pipeline context](https://docs.crossplane.io/v1.15/concepts/composition-functions/#function-pipeline-context).

This [function-environment-configs](https://github.com/crossplane-contrib/function-environment-configs) writes the EnvironmentConfig in the context which is not usable in this function atm.

I would like to use EnvironmentConfigs to have a common config per 'environment'.

**Comment by Peefy** [comment]
@aleeriz  Thank you. I've opened a PR to impl this feature. https://github.com/crossplane-contrib/function-kcl/pull/65

**Comment by aleeriz** [comment]
Thanks @Peefy, could you do a release 🙏

**Comment by Peefy** [comment]
Okay, I've released the function-kcl v0.5.0 https://marketplace.upbound.io/functions/crossplane-contrib/function-kcl/v0.5.0
