### ISSUE TITLE
Write to Composite Resource

### ISSUE THREAD

**Issue by vfarcic** [crossplane-contrib/function-kcl#84]
### What problem are you facing?

I don't see the option to write back to the Composite resource. According to https://github.com/crossplane-contrib/function-kcl?tab=readme-ov-file#guides-for-developing-kcl `option` can be used only to read, not to write.

### How could this Function help solve your problem?

Add a feature equivalent to the `ToCompositeFieldPath` Patch and Transform `type`. An example:

```
    - type: ToCompositeFieldPath
      fromFieldPath: spec.forProvider.manifest.spec.rules[0].host
      toFieldPath: status.host 
```

**Comment by Peefy** [comment]
@vfarcic Sorry, I haven't updated the document yet. The current version of `function-kcl` already supports the status field of patch XR. You can refer to the example [here](https://github.com/crossplane-contrib/function-kcl/blob/main/examples/default/connection_details/composition.yaml#L28) to patch XR and put it into the `items` field to return it as a whole.

**Comment by vfarcic** [comment]
Thanks a ton.
