### ISSUE TITLE
[Enhancement] Support function-kcl to obtain parameters from external ConfigMaps

### ISSUE THREAD

**Issue by Peefy** [crossplane-contrib/function-kcl#86]

**Comment by negz** [comment]
We typically discourage functions from talking to the API server directly to load additional inputs (e.g. from a ConfigMap). Ideally Crossplane mediates all interactions of the function. This means that folks don't need to worry about configuring the function's RBAC permissions. It also means a function could be deployed outside of a cluster in future and still work fine.

Can you share more about what you want to achieve by loading parameters from a ConfigMap?

**Comment by Peefy** [comment]
Thank you! At present, this is not a real scenario demand. Thank you for providing the information. I will close this issue. 🤗
