### ISSUE TITLE
Container uses 5GB of ram sitting mostly idle

### ISSUE THREAD

**Issue by empath-nirvana** [crossplane-contrib/function-kcl#88]
Looking at my datadog metrics, it seems to be consuming 5GB of ram at all times (using, not requested), this is more than any of my very heavily used crossplane providers (most of which use less than 1GB of ram.  Is there anything that can be done to reduce memory consumption?  I'm only syncing one composition with this currently so it's very lightly used.

**Comment by Peefy** [comment]
Hello. Thank you for the feedback. May I ask if the function occupied 5G of memory when it was first deployed, or if the memory usage after a period of use may be due to memory leakage.

**Comment by empath-nirvana** [comment]
![Screenshot 2024-04-29 at 11 55 32 AM](https://github.com/crossplane-contrib/function-kcl/assets/86739375/498f329c-6db9-4419-951a-7ee3fdaf35f5)

Seems like a memory leak -- it was steady at 25-50MB until it shot up to 5GB over the course of about 10 days and stayed steady there.  I deleted the pod and it's back to 25MB currently.

**Comment by Peefy** [comment]
Make sense. I will release a new function version without the memory leak later. Thanks for the feedback.
