### ISSUE TITLE
Meta type error when building the package

### ISSUE THREAD

**Issue by zargor** [crossplane-contrib/function-kcl#94]
### What happened?
When try to build the package, I get the following error:
```
crossplane: error: failed to build package: not exactly one package meta type
```

### How can we reproduce it?
It was working. But suddenly just started to fail. The command is from README.md development chapter:
```
# Build a function package - see package/crossplane.yaml
$ crossplane xpkg build -f package --embed-runtime-image=kcllang/crossplane-kcl
```

### What environment did it happen in?
This happens as a result of local development.

**Comment by zargor** [comment]
I removed `crossplane.yaml` by accident. Closing the issue.

**Comment by Peefy** [comment]
No worries. Communicate anytime if you have any questions.
