### ISSUE TITLE
Extract data from a specific resource

### ISSUE THREAD

**Issue by vfarcic** [crossplane-contrib/function-kcl#96]
### What problem are you facing?

I'm not sure how to extract data from a specific composed resource by using `kind` and `metadata.name`. I'm guessing that it should be inside `ocds` but I'm not sure what the structure of it is. Is there an example I could use?

P.S. I apologize if this is already explained in one of the examples (and I missed it).

**Comment by vfarcic** [comment]
Found it.

**Comment by Peefy** [comment]
Sorry, I seem to have forgotten to mention it in the document. I will improve it later. 😷
