### ISSUE TITLE
KCLInput vs KCLRun

### ISSUE THREAD

**Issue by jgascon-nx** [crossplane-contrib/function-kcl#98]
In the Crossplane Marketplace one can find the `KCLInput`.`template.fn.crossplane.io/v1beta1` specification ([here](https://marketplace.upbound.io/functions/crossplane-contrib/function-kcl)).

However, all the provided examples here use `KCLRun`.`krm.kcl.dev/v1alpha1`.

Both CRDs have not the same spec (For instance, you cannot set `target: Default` in `KCLInput`), so I was wondering:
- Is there any available info about the difference? I think that more clues about this could avoid a bit of confusion (Like mine :( )
- Are they supposed to share the same spec?  (but maybe they are different because the XP CRDs need to be in a XP group?)
  - In this case, spec diffs (Example: `spec.target` - [KCLInput](https://github.com/crossplane-contrib/function-kcl/blob/dacde802c58dccc120c5189b20eda75dad2dace1/package/input/template.fn.crossplane.io_kclinputs.yaml#L69-L77) spec vs [KCLRun](https://github.com/crossplane-contrib/function-kcl/?tab=readme-ov-file#target-support) doc) )

Thanks!

**Comment by Peefy** [comment]
Hello, krm kcl is currently undergoing refactoring and can be seen as an integrated interface between the KCL ecosystem and Kubernetes ecosystem tools. It defines some general specifications, methods, and implementations, namely what input and output parameters are, and what fields are. Different tools can be extended or partially implemented based on this specification.

Additionally, the specification defined in krm kcl is not a deployable resource, it does not have a CRD, and you can simply consider it as a public component.

Thank you for your feedback. I will supplement the complete documentation for this area in the future when the refactor is finished.

**Comment by jgascon-nx** [comment]
Thank you for the clarifications!
